# Generated by Django 5.1.3 on 2024-12-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
