# Generated by Django 5.1.3 on 2024-12-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_payment_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='public_key',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
