# Generated by Django 5.1.3 on 2024-12-01 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_payment_public_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='role',
        ),
    ]
