# Generated by Django 5.1.3 on 2024-12-01 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_payment_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
    ]
