# Generated by Django 5.1.3 on 2024-12-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_payment_customer_name_alter_systemuser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemuser',
            name='user',
        ),
        migrations.AddField(
            model_name='systemuser',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='systemuser',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='systemuser',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='gender',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='mobile',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='role',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
