# Generated by Django 5.1.3 on 2024-12-06 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_systemuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemuser',
            name='password',
        ),
    ]
