# Generated by Django 5.1.3 on 2024-12-06 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_systemuser_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemuser',
            name='image',
        ),
    ]
